### PR TITLE
Workaround for IE9 compatiblity (not supporting classList)

### PR DESCRIPTION
**Pull request by Redfern**
Noticed an issue with IE9 and lower not supporting document.body.classList.add, so i've modified the .js to allow for this.

### CODE REVIEW

**Comment by kyleshevlin** [comment]
Hey, thanks for the pull request. I have a busy night ahead of me, but I'll try and take a good look at this tomorrow (and figure out why Travis failed, been a while since I did anything with this project).

My one concern I have with your PR is that I'm pretty certain these classes are now getting added to the `<html>` element, and not the `<body>` element. Is there an >= IE9 way of targeting to the `<body>`? I'm sure there is, I just need to look it up, but that's the question I would be trying to answer.

**Comment by Redfern** [comment]
I've had a look and it is down to the class not getting added to the body:

"PhantomJS 2.1.1 (Windows 8 0.0.0) Matchbox .init() should add initClass to body FAILED
        Expected '' to be 'js-matchbox-initialized'."

It looks like you should just be able to swap: document.documentElement for either document.body or document.querySelector('body')

**Comment by kyleshevlin** [comment]
Hey @Redfern, I went ahead and made a small adjustment to Matchbox just now, merged in #9. I don't have an IE9 machine handy to me, I'm assuming since you added support you might be able to check that this new version will work. In theory, it should. If it works, I'm going to close this pull request and publish the new version to NPM. Thanks for bringing this to my attention. I appreciate it.

**Comment by kyleshevlin** [comment]
I mistakenly understood the problem. IE9 supports `document.body`, it does not support `classList`. My apologies. If you want to update your PR so that it uses `document.body` instead of `document.documentElement` I think I can merge your PR, @Redfern.

**Comment by Redfern** [comment]
No problem, i've made the change now @kyleshevlin

**Pull request merged**
